API_HOST_URL: 'https://aulanet.com.bo' # localhost is 10.0.2.2 in Android
ENVIRONMENT_DISPLAY_NAME: 'AulaNet'
PLATFORM_NAME: 'AulaNET'
PLATFORM_DESTINATION_NAME: 'aulanet.com.bo'
FEEDBACK_EMAIL_ADDRESS: 'soporte@aulanet.com.bo'
OAUTH_CLIENT_ID: 'android'
